In [1]:
import numpy as np


np.random.seed(42)


seq_len = 6
d_model = 8
d_k     = 4


X   = np.random.randn(seq_len, d_model)
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)


Q = X @ W_Q
K = X @ W_K
V = X @ W_V


scores        = Q @ K.T
scaled_scores = scores / np.sqrt(d_k)


def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / e.sum(axis=-1, keepdims=True)


attn_weights = softmax(scaled_scores)
output       = attn_weights @ V


print(attn_weights.round(4))
print(output.round(4))


[[0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00]
 [9.494e-01 0.000e+00 5.050e-02 0.000e+00 0.000e+00 1.000e-04]
 [0.000e+00 0.000e+00 1.000e-04 0.000e+00 9.999e-01 0.000e+00]
 [9.481e-01 0.000e+00 1.000e-04 5.150e-02 0.000e+00 3.000e-04]
 [9.600e-01 1.000e-04 3.940e-02 0.000e+00 0.000e+00 5.000e-04]
 [9.904e-01 0.000e+00 5.000e-04 8.600e-03 0.000e+00 4.000e-04]]
[[ 0.416   3.1783 -4.0227  1.9093]
 [ 0.492   4.0024 -0.1643 -3.6369]
 [ 3.1574 -2.5679  1.2379 -2.6127]
 [ 0.5942  4.5572 -0.4193 -3.6044]
 [ 0.5171  4.1405 -0.1769 -3.694 ]
 [ 0.6013  4.6138 -0.2557 -3.8509]]
